# Operaciones declarativas por tabla. No contiene SQL ni conexiones.
OPERACIONES_TABLA = {'SEGURIDAD_0001': {'accion': 'consultar',
                    'tabla': 'usuarios',
                    'columnas': 'id',
                    'filtros_texto': 'usuario=?',
                    'orden_texto': '',
                    'limite': None},
 'SEGURIDAD_0002': {'accion': 'editar',
                    'tabla': 'usuarios',
                    'asignaciones_texto': 'nombre=?, password_hash=?, rol=?, activo=1, intentos_fallidos=0, '
                                          'requiere_cambio_pass=0',
                    'filtros_texto': 'usuario=?'},
 'SEGURIDAD_0003': {'accion': 'crear',
                    'tabla': 'usuarios',
                    'columnas': ['usuario',
                                 'nombre',
                                 'password_hash',
                                 'rol',
                                 'activo',
                                 'intentos_fallidos',
                                 'requiere_cambio_pass',
                                 'creado_en'],
                    'upsert': False,
                    'ignorar': False},
 'SEGURIDAD_0004': {'accion': 'consultar',
                    'tabla': 'usuarios',
                    'columnas': 'id,usuario,nombre,password_hash,rol,activo,COALESCE(intentos_fallidos,0),COALESCE(requiere_cambio_pass,0)',
                    'filtros_texto': 'usuario=?',
                    'orden_texto': '',
                    'limite': None},
 'SEGURIDAD_0005': {'accion': 'editar',
                    'tabla': 'usuarios',
                    'asignaciones_texto': 'intentos_fallidos=0',
                    'filtros_texto': 'id=?'},
 'SEGURIDAD_0006': {'accion': 'editar',
                    'tabla': 'usuarios',
                    'asignaciones_texto': 'intentos_fallidos=?, activo=?',
                    'filtros_texto': 'id=?'},
 'SERVICIOS_0007': {'accion': 'consultar',
                    'tabla': 'catalogo_naves_lineas',
                    'columnas': 'nave,linea_norm,sector_norm',
                    'filtros_texto': 'activo=1',
                    'orden_texto': '',
                    'limite': None},
 'SERVICIOS_0008': {'accion': 'consultar',
                    'tabla': 'catalogo_formatos_entrega',
                    'columnas': 'linea,sector,tipo_analisis,orden_linea,orden_sector',
                    'filtros_texto': 'formato_nave=? AND tipo=? AND activo=1',
                    'orden_texto': 'orden_linea,orden_sector,id',
                    'limite': None},
 'SERVICIOS_0009': {'accion': 'consultar',
                    'tabla': 'catalogo_seguimientos_entrega',
                    'columnas': 'nombre',
                    'filtros_texto': 'activo=1',
                    'orden_texto': 'orden,id',
                    'limite': None},
 'SERVICIOS_0010': {'accion': 'consultar',
                    'tabla': 'catalogo_seguimientos_entrega',
                    'columnas': 'id,nombre',
                    'filtros_texto': 'activo=1',
                    'orden_texto': 'orden,id',
                    'limite': None},
 'SERVICIOS_0011': {'accion': 'consultar',
                    'tabla': 'catalogo_seguimientos_campos',
                    'columnas': 'id,nombre,tipo_campo,opciones,obligatorio,orden',
                    'filtros_texto': 'seguimiento_id=? AND activo=1',
                    'orden_texto': 'orden,id',
                    'limite': None},
 'SERVICIOS_0012': {'accion': 'consultar',
                    'tabla': 'catalogos',
                    'columnas': 'valor',
                    'filtros_texto': 'categoria=? AND activo=1',
                    'orden_texto': 'valor',
                    'limite': None},
 'SERVICIOS_0013': {'accion': 'crear',
                    'tabla': 'matriz_entrega',
                    'columnas': ['fecha',
                                 'analista',
                                 'entrega_id',
                                 'total_carga_datos',
                                 'horas_nave1',
                                 'horas_nave2',
                                 'horas_nave3',
                                 'actualizado_en'],
                    'upsert': False,
                    'ignorar': False},
 'SERVICIOS_0014': {'accion': 'crear',
                    'tabla': 'auditoria',
                    'columnas': ['usuario', 'accion', 'detalle', 'fecha_hora'],
                    'upsert': False,
                    'ignorar': False},
 'SERVICIOS_0015': {'accion': 'consultar',
                    'tabla': 'pnc_registros',
                    'columnas': 'folio',
                    'filtros_texto': 'folio LIKE ?',
                    'orden_texto': 'folio DESC',
                    'limite': 1},
 'SERVICIOS_0016': {'accion': 'consultar',
                    'tabla': 'ajustes_diarios_spac',
                    'columnas': 'entidad,fecha,valor',
                    'filtros_texto': 'tipo_entidad=?',
                    'orden_texto': '',
                    'limite': None},
 'SERVICIOS_0017': {'accion': 'consultar',
                    'tabla': 'metas_carga_spac',
                    'columnas': 'entidad,periodo_clave,meta',
                    'filtros_texto': 'tipo_entidad=? AND periodo_tipo=?',
                    'orden_texto': 'periodo_clave,entidad',
                    'limite': None},
 'SERVICIOS_0018': {'accion': 'consultar',
                    'tabla': 'matriz_entrega',
                    'columnas': 'fecha,analista,total_carga_datos,horas_nave1,horas_nave2,horas_nave3',
                    'filtros_texto': '',
                    'orden_texto': '',
                    'limite': None},
 'SERVICIOS_0019': {'accion': 'consultar',
                    'tabla': 'ajustes_diarios_spac',
                    'columnas': 'entidad,fecha,valor',
                    'filtros_texto': 'tipo_entidad=?',
                    'orden_texto': '',
                    'limite': None},
 'SERVICIOS_0020': {'accion': 'vista', 'nombre': 'vista_servicios_0020'},
 'REPORTES_0021': {'accion': 'consultar',
                   'tabla': 'pnc_registros',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'REPORTES_0022': {'accion': 'consultar',
                   'tabla': 'pnc_registros',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'REPORTES_0023': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'REPORTES_0024': {'accion': 'consultar',
                   'tabla': 'entregas_turno',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'REPORTES_0025': {'accion': 'consultar',
                   'tabla': 'entregas_turno_lineas',
                   'columnas': '*',
                   'filtros_texto': 'entrega_id=?',
                   'orden_texto': 'orden_fila',
                   'limite': None},
 'REPORTES_0026': {'accion': 'consultar',
                   'tabla': 'matriz_entrega',
                   'columnas': '*',
                   'filtros_texto': 'entrega_id=?',
                   'orden_texto': '',
                   'limite': None},
 'REPORTES_0027': {'accion': 'consultar',
                   'tabla': 'entregas_turno_seguimientos',
                   'columnas': '*',
                   'filtros_texto': 'entrega_id=?',
                   'orden_texto': 'bloque,orden_fila,id',
                   'limite': None},
 'INTERFAZ_0028': {'accion': 'editar',
                   'tabla': 'usuarios',
                   'asignaciones_texto': 'password_hash=?,requiere_cambio_pass=0,intentos_fallidos=0',
                   'filtros_texto': 'usuario=?'},
 'INTERFAZ_0029': {'accion': 'recurso', 'nombre': 'estilos'},
 'INTERFAZ_0030': {'accion': 'vista', 'nombre': 'vista_interfaz_0030'},
 'INTERFAZ_0031': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0032': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': 'codigo,defecto',
                   'filtros_texto': '',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0033': {'accion': 'consultar',
                   'tabla': 'metas_carga_spac',
                   'columnas': 'entidad,meta',
                   'filtros_texto': 'tipo_entidad=? AND periodo_tipo=? AND periodo_clave=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0034': {'accion': 'crear',
                   'tabla': 'metas_carga_spac',
                   'columnas': ['tipo_entidad',
                                'entidad',
                                'periodo_tipo',
                                'periodo_clave',
                                'meta',
                                'actualizado_por',
                                'actualizado_en'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0035': {'accion': 'eliminar',
                   'tabla': 'ajustes_diarios_spac',
                   'filtros_texto': 'tipo_entidad=? AND entidad=? AND fecha=?'},
 'INTERFAZ_0036': {'accion': 'crear',
                   'tabla': 'ajustes_diarios_spac',
                   'columnas': ['tipo_entidad',
                                'entidad',
                                'fecha',
                                'valor',
                                'justificacion',
                                'actualizado_por',
                                'actualizado_en'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0037': {'accion': 'vista', 'nombre': 'vista_interfaz_0037'},
 'INTERFAZ_0038': {'accion': 'eliminar', 'tabla': 'entregas_turno_seguimientos', 'filtros_texto': 'entrega_id=?'},
 'INTERFAZ_0039': {'accion': 'eliminar', 'tabla': 'entregas_turno_lineas', 'filtros_texto': 'entrega_id=?'},
 'INTERFAZ_0040': {'accion': 'eliminar', 'tabla': 'entregas_turno', 'filtros_texto': 'id=?'},
 'INTERFAZ_0041': {'accion': 'eliminar', 'tabla': 'matriz_entrega', 'filtros_texto': 'id=?'},
 'INTERFAZ_0042': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0043': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0044': {'accion': 'crear',
                   'tabla': '{0}',
                   'columnas': ['dia',
                                'mes',
                                'anio',
                                'nave',
                                'linea_sector',
                                'familia',
                                'equipo_hallazgo',
                                'item',
                                'producto',
                                'lote',
                                'descripcion_hallazgo',
                                'tipo',
                                'particulas_halladas',
                                'accion_contingente',
                                'investigacion_origen',
                                'analista_detecta',
                                'supervisor_responsable',
                                'acciones_evitar_incidencia',
                                'creado_por',
                                'creado_en',
                                'etapa',
                                'codigo_defecto',
                                'semana',
                                'turno',
                                'responsable_detecta',
                                'acciones_inmediatas',
                                'disposicion',
                                'cantidad_observada',
                                'status',
                                'categoria_inicial',
                                'sector_hallazgo',
                                'ubicacion_material'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0045': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0046': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0047': {'accion': 'crear',
                   'tabla': 'devoluciones_registros',
                   'columnas': ['fecha',
                                'codigo_defecto',
                                'defecto',
                                'cedis',
                                'pais_estado',
                                'item',
                                'producto',
                                'cliente',
                                'linea',
                                'familia',
                                'lote',
                                'caducidad',
                                'descripcion_defecto',
                                'comprobado',
                                'cantidad_afectada',
                                'unidad',
                                'sector',
                                'disposicion',
                                'tsp_numero',
                                'status',
                                'nave',
                                'creado_por',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0048': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0049': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0050': {'accion': 'consultar',
                   'tabla': 'reclamos_registros',
                   'columnas': 'id',
                   'filtros_texto': 'UPPER(TRIM(numero_caso))=UPPER(TRIM(?))',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0051': {'accion': 'crear',
                   'tabla': 'reclamos_registros',
                   'columnas': ['fecha',
                                'codigo_defecto',
                                'descripcion_defecto',
                                'fuente',
                                'mercado',
                                'pais_estado',
                                'numero_caso',
                                'item',
                                'producto',
                                'cliente',
                                'familia',
                                'descripcion_reclamo',
                                'causa_raiz',
                                'acciones_correctivas_contingentes',
                                'comprobado',
                                'cantidad_afectada',
                                'unidad',
                                'sector',
                                'estado_reclamo',
                                'fecha_cierre',
                                'tsp_numero',
                                'caducidad',
                                'lote',
                                'nave',
                                'pmd',
                                'tipo_defecto',
                                'clasificacion_defecto',
                                'red_social',
                                'creado_por',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0052': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0053': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0054': {'accion': 'crear',
                   'tabla': 'pnc_registros',
                   'columnas': ['folio',
                                'fecha_apertura',
                                'linea_sector',
                                'nave',
                                'item',
                                'descripcion_producto',
                                'cliente',
                                'familia',
                                'lote',
                                'etapa',
                                'codigo_defecto',
                                'defecto',
                                'tipo_defecto',
                                'clasificacion',
                                'turno',
                                'supervisor',
                                'analista',
                                'responsable_detecta',
                                'descripcion_defecto',
                                'acciones_inmediatas',
                                'disposicion',
                                'cantidad_observada',
                                'cantidad_reproceso',
                                'cantidad_decomiso',
                                'cantidad_aprobado_segunda',
                                'cantidad_total_pnc',
                                'status',
                                'fecha_final_tratamiento',
                                'observaciones',
                                'material_hallado',
                                'creado_por',
                                'creado_en',
                                'semana',
                                'categoria_inicial_pnc',
                                'categoria_final_pnc'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0055': {'accion': 'eliminar', 'tabla': '{0}', 'filtros_texto': 'id=?'},
 'INTERFAZ_0056': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0057': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0058': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0059': {'accion': 'columnas', 'tabla': '{0}'},
 'INTERFAZ_0060': {'accion': 'editar', 'tabla': '{0}', 'asignaciones_texto': '{1}', 'filtros_texto': 'id=?'},
 'INTERFAZ_0061': {'accion': 'consultar',
                   'tabla': 'pnc_registros',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id ASC',
                   'limite': None},
 'INTERFAZ_0062': {'accion': 'consultar',
                   'tabla': 'me_registros',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id ASC',
                   'limite': None},
 'INTERFAZ_0063': {'accion': 'consultar',
                   'tabla': 'ddm_rx_registros',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id ASC',
                   'limite': None},
 'INTERFAZ_0064': {'accion': 'consultar',
                   'tabla': 'reclamos_registros',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id ASC',
                   'limite': None},
 'INTERFAZ_0065': {'accion': 'consultar',
                   'tabla': 'reclamos_registros',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0066': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0067': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0068': {'accion': 'consultar',
                   'tabla': 'reclamos_registros',
                   'columnas': 'id',
                   'filtros_texto': 'UPPER(TRIM(numero_caso))=UPPER(TRIM(?)) AND id<>?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0069': {'accion': 'editar',
                   'tabla': 'reclamos_registros',
                   'asignaciones_texto': 'fecha=?,codigo_defecto=?,descripcion_defecto=?,fuente=?,mercado=?,pais_estado=?,numero_caso=?,item=?,producto=?,cliente=?,familia=?,descripcion_reclamo=?,causa_raiz=?,acciones_correctivas_contingentes=?,comprobado=?,cantidad_afectada=?,unidad=?,sector=?,estado_reclamo=?,fecha_cierre=?,tsp_numero=?,caducidad=?,lote=?,nave=?,pmd=?,tipo_defecto=?,clasificacion_defecto=?,red_social=?,actualizado_por=?,actualizado_en=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0070': {'accion': 'consultar',
                   'tabla': 'devoluciones_registros',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id ASC',
                   'limite': None},
 'INTERFAZ_0071': {'accion': 'consultar',
                   'tabla': 'devoluciones_registros',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0072': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0073': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': '*',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0074': {'accion': 'editar',
                   'tabla': 'devoluciones_registros',
                   'asignaciones_texto': 'fecha=?,codigo_defecto=?,defecto=?,cedis=?,pais_estado=?,item=?,producto=?,cliente=?,familia=?,lote=?,caducidad=?,descripcion_defecto=?,comprobado=?,cantidad_afectada=?,unidad=?,sector=?,disposicion=?,tsp_numero=?,status=?,nave=?,actualizado_por=?,actualizado_en=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0075': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'item,descripcion',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0076': {'accion': 'crear',
                   'tabla': '{0}',
                   'columnas': ['item',
                                'descripcion',
                                'lote',
                                'destino',
                                'numero_muestras',
                                'numero_corrugado',
                                'responsable',
                                'observaciones',
                                'creado_por',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0077': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'item,descripcion',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0078': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id DESC',
                   'limite': None},
 'INTERFAZ_0079': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0080': {'accion': 'editar',
                   'tabla': '{0}',
                   'asignaciones_texto': 'item=?,descripcion=?,lote=?,destino=?,numero_muestras=?,numero_corrugado=?,responsable=?,observaciones=?,actualizado_por=?,actualizado_en=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0081': {'accion': 'eliminar', 'tabla': '{0}', 'filtros_texto': 'id=?'},
 'INTERFAZ_0082': {'accion': 'consultar',
                   'tabla': 'matriz_entrega',
                   'columnas': 'id',
                   'filtros_texto': 'fecha=? AND analista=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0083': {'accion': 'crear',
                   'tabla': 'entregas_turno',
                   'columnas': ['nave',
                                'fecha',
                                'analista',
                                'turno',
                                'referencia',
                                'total_carga_datos',
                                'total_horas_trabajadas',
                                'creado_por',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0084': {'accion': 'crear',
                   'tabla': 'entregas_turno_lineas',
                   'columnas': ['entrega_id',
                                'grupo',
                                'linea',
                                'producto_descripcion',
                                'horas_trabajadas',
                                'carga_spac',
                                'observaciones',
                                'orden_fila',
                                'nave_catalogo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0085': {'accion': 'crear',
                   'tabla': 'entregas_turno_lineas',
                   'columnas': ['entrega_id',
                                'grupo',
                                'linea',
                                'producto_descripcion',
                                'horas_trabajadas',
                                'carga_spac',
                                'observaciones',
                                'orden_fila'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0086': {'accion': 'crear',
                   'tabla': 'entregas_turno_seguimientos',
                   'columnas': ['entrega_id',
                                'bloque',
                                'registro_numero',
                                'hoja_fisica',
                                'carga_electronica',
                                'correo',
                                'descripcion_seguimiento',
                                'datos_json',
                                'orden_fila'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0087': {'accion': 'consultar',
                   'tabla': 'matriz_entrega',
                   'columnas': 'id',
                   'filtros_texto': 'fecha=? AND analista=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0088': {'accion': 'crear',
                   'tabla': 'entregas_turno',
                   'columnas': ['nave',
                                'fecha',
                                'analista',
                                'turno',
                                'referencia',
                                'total_carga_datos',
                                'total_horas_trabajadas',
                                'creado_por',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0089': {'accion': 'crear',
                   'tabla': 'entregas_turno_lineas',
                   'columnas': ['entrega_id',
                                'grupo',
                                'linea',
                                'producto_descripcion',
                                'horas_trabajadas',
                                'carga_spac',
                                'observaciones',
                                'orden_fila',
                                'nave_catalogo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0090': {'accion': 'crear',
                   'tabla': 'entregas_turno_seguimientos',
                   'columnas': ['entrega_id',
                                'bloque',
                                'registro_numero',
                                'hoja_fisica',
                                'carga_electronica',
                                'correo',
                                'descripcion_seguimiento',
                                'datos_json',
                                'orden_fila'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0091': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'id,item,descripcion,cliente,familia',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0092': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'id,activo',
                   'filtros_texto': 'item=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0093': {'accion': 'editar',
                   'tabla': 'productos',
                   'asignaciones_texto': 'descripcion=?,cliente=?,familia=?,activo=1',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0094': {'accion': 'crear',
                   'tabla': 'productos',
                   'columnas': ['item', 'descripcion', 'cliente', 'familia', 'activo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0095': {'accion': 'consultar',
                   'tabla': '{0}',
                   'columnas': '*',
                   'filtros_texto': 'id=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0096': {'accion': 'editar', 'tabla': '{0}', 'asignaciones_texto': 'activo=0', 'filtros_texto': 'id=?'},
 'INTERFAZ_0097': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'id,item,descripcion,cliente,familia',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'descripcion',
                   'limite': None},
 'INTERFAZ_0098': {'accion': 'crear',
                   'tabla': 'productos',
                   'columnas': ['item', 'descripcion', 'cliente', 'familia', 'activo'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0099': {'accion': 'editar',
                   'tabla': 'productos',
                   'asignaciones_texto': 'item=?,descripcion=?,cliente=?,familia=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0100': {'accion': 'consultar',
                   'tabla': 'productos',
                   'columnas': 'id',
                   'filtros_texto': 'item=? AND descripcion=? AND cliente=? AND familia=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0101': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': 'id,codigo,defecto,tipo_defecto,clasificacion',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'CAST(codigo AS INTEGER)',
                   'limite': None},
 'INTERFAZ_0102': {'accion': 'crear',
                   'tabla': 'defectos',
                   'columnas': ['codigo', 'defecto', 'tipo_defecto', 'clasificacion', 'activo'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0103': {'accion': 'editar',
                   'tabla': 'defectos',
                   'asignaciones_texto': 'codigo=?,defecto=?,tipo_defecto=?,clasificacion=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0104': {'accion': 'consultar',
                   'tabla': 'defectos',
                   'columnas': 'id',
                   'filtros_texto': 'codigo=? AND defecto=? AND tipo_defecto=? AND clasificacion=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0105': {'accion': 'consultar',
                   'tabla': 'catalogos',
                   'columnas': 'id,categoria,valor',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'categoria,valor',
                   'limite': None},
 'INTERFAZ_0106': {'accion': 'consultar',
                   'tabla': 'catalogos',
                   'columnas': 'id',
                   'filtros_texto': 'categoria=? AND valor=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0107': {'accion': 'crear',
                   'tabla': 'catalogos',
                   'columnas': ['categoria', 'valor', 'activo'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0108': {'accion': 'consultar',
                   'tabla': 'catalogos',
                   'columnas': 'id',
                   'filtros_texto': 'categoria=? AND valor=? AND id<>? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0109': {'accion': 'editar',
                   'tabla': 'catalogos',
                   'asignaciones_texto': 'categoria=?,valor=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0110': {'accion': 'editar', 'tabla': 'catalogos', 'asignaciones_texto': 'activo=0', 'filtros_texto': 'id=?'},
 'INTERFAZ_0111': {'accion': 'consultar',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': 'id,nave,linea,sector,orden',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'nave,orden,id',
                   'limite': None},
 'INTERFAZ_0112': {'accion': 'consultar',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': 'id',
                   'filtros_texto': 'nave=? AND linea_norm=? AND sector_norm=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0113': {'accion': 'consultar',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': 'COALESCE(MAX(orden),-1)+1 AS n',
                   'filtros_texto': 'nave=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0114': {'accion': 'crear',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': ['nave', 'linea', 'sector', 'linea_norm', 'sector_norm', 'orden', 'activo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0115': {'accion': 'consultar',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': '*',
                   'filtros_texto': 'id=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0116': {'accion': 'consultar',
                   'tabla': 'catalogo_naves_lineas',
                   'columnas': 'id',
                   'filtros_texto': 'nave=? AND linea_norm=? AND sector_norm=? AND id<>? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0117': {'accion': 'editar',
                   'tabla': 'catalogo_naves_lineas',
                   'asignaciones_texto': 'nave=?,linea=?,sector=?,linea_norm=?,sector_norm=?,orden=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0118': {'accion': 'editar',
                   'tabla': 'catalogo_naves_lineas',
                   'asignaciones_texto': 'activo=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0119': {'accion': 'consultar',
                   'tabla': 'catalogo_formatos_entrega',
                   'columnas': 'id,linea,sector,tipo_analisis,orden_linea,orden_sector',
                   'filtros_texto': 'formato_nave=? AND tipo=? AND activo=1',
                   'orden_texto': 'orden_linea,orden_sector,id',
                   'limite': None},
 'INTERFAZ_0120': {'accion': 'consultar',
                   'tabla': 'catalogo_formatos_entrega',
                   'columnas': 'id',
                   'filtros_texto': 'formato_nave=? AND tipo=? AND linea=? AND sector=? AND tipo_analisis=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0121': {'accion': 'crear',
                   'tabla': 'catalogo_formatos_entrega',
                   'columnas': ['formato_nave',
                                'tipo',
                                'linea',
                                'sector',
                                'tipo_analisis',
                                'orden_linea',
                                'orden_sector',
                                'activo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0122': {'accion': 'editar',
                   'tabla': 'catalogo_formatos_entrega',
                   'asignaciones_texto': 'activo=1,orden_linea=?,orden_sector=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0123': {'accion': 'consultar',
                   'tabla': 'catalogo_formatos_entrega',
                   'columnas': '*',
                   'filtros_texto': 'id=? AND activo=1',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0124': {'accion': 'consultar',
                   'tabla': 'catalogo_formatos_entrega',
                   'columnas': 'id',
                   'filtros_texto': 'formato_nave=? AND tipo=? AND linea=? AND sector=? AND tipo_analisis=? AND id<>? '
                                    'AND activo=1',
                   'orden_texto': '',
                   'limite': 1},
 'INTERFAZ_0125': {'accion': 'editar',
                   'tabla': 'catalogo_formatos_entrega',
                   'asignaciones_texto': 'linea=?,sector=?,tipo_analisis=?,orden_linea=?,orden_sector=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0126': {'accion': 'editar',
                   'tabla': 'catalogo_formatos_entrega',
                   'asignaciones_texto': 'activo=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0127': {'accion': 'consultar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'columnas': 'id,nombre,orden',
                   'filtros_texto': 'activo=1',
                   'orden_texto': 'orden,id',
                   'limite': None},
 'INTERFAZ_0128': {'accion': 'consultar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'columnas': 'id',
                   'filtros_texto': 'UPPER(TRIM(nombre))=UPPER(TRIM(?))',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0129': {'accion': 'editar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'asignaciones_texto': 'nombre=?,orden=?,activo=1',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0130': {'accion': 'crear',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'columnas': ['nombre', 'orden', 'activo'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0131': {'accion': 'consultar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0132': {'accion': 'consultar',
                   'tabla': 'catalogo_seguimientos_campos',
                   'columnas': 'id,nombre,tipo_campo,opciones,obligatorio,orden',
                   'filtros_texto': 'seguimiento_id=? AND activo=1',
                   'orden_texto': 'orden,id',
                   'limite': None},
 'INTERFAZ_0133': {'accion': 'crear',
                   'tabla': 'catalogo_seguimientos_campos',
                   'columnas': ['seguimiento_id', 'nombre', 'tipo_campo', 'opciones', 'obligatorio', 'orden', 'activo'],
                   'upsert': True,
                   'ignorar': False},
 'INTERFAZ_0134': {'accion': 'editar',
                   'tabla': 'catalogo_seguimientos_campos',
                   'asignaciones_texto': 'nombre=?,tipo_campo=?,opciones=?,obligatorio=?,orden=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0135': {'accion': 'editar',
                   'tabla': 'catalogo_seguimientos_campos',
                   'asignaciones_texto': 'activo=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0136': {'accion': 'editar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'asignaciones_texto': 'nombre=?,orden=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0137': {'accion': 'editar',
                   'tabla': 'catalogo_seguimientos_entrega',
                   'asignaciones_texto': 'activo=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0138': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': 'id,usuario,nombre,rol,COALESCE(intentos_fallidos,0) AS intentos_fallidos',
                   'filtros_texto': 'activo=0',
                   'orden_texto': 'intentos_fallidos DESC,usuario',
                   'limite': None},
 'INTERFAZ_0139': {'accion': 'editar',
                   'tabla': 'usuarios',
                   'asignaciones_texto': 'activo=1,intentos_fallidos=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0140': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': 'id',
                   'filtros_texto': 'usuario=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0141': {'accion': 'crear',
                   'tabla': 'usuarios',
                   'columnas': ['usuario',
                                'nombre',
                                'password_hash',
                                'rol',
                                'activo',
                                'intentos_fallidos',
                                'requiere_cambio_pass',
                                'creado_en'],
                   'upsert': False,
                   'ignorar': False},
 'INTERFAZ_0142': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': 'id,usuario,nombre,rol,COALESCE(intentos_fallidos,0) AS '
                               'intentos_fallidos,COALESCE(requiere_cambio_pass,0) AS requiere_cambio_pass,CASE WHEN '
                               "activo=1 THEN 'Habilitado' ELSE 'Bloqueado / Inhabilitado' END AS estado,creado_en",
                   'filtros_texto': '',
                   'orden_texto': 'id',
                   'limite': None},
 'INTERFAZ_0143': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': '*',
                   'filtros_texto': 'id=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0144': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': 'id',
                   'filtros_texto': 'usuario=? AND id<>?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0145': {'accion': 'editar',
                   'tabla': 'usuarios',
                   'asignaciones_texto': 'usuario=?,nombre=?,rol=?,password_hash=?,requiere_cambio_pass=1,intentos_fallidos=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0146': {'accion': 'editar',
                   'tabla': 'usuarios',
                   'asignaciones_texto': 'usuario=?,nombre=?,rol=?',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0147': {'accion': 'consultar',
                   'tabla': 'usuarios',
                   'columnas': 'id',
                   'filtros_texto': 'usuario=?',
                   'orden_texto': '',
                   'limite': None},
 'INTERFAZ_0148': {'accion': 'editar', 'tabla': 'usuarios', 'asignaciones_texto': 'activo=0', 'filtros_texto': 'id=?'},
 'INTERFAZ_0149': {'accion': 'editar',
                   'tabla': 'usuarios',
                   'asignaciones_texto': 'activo=1,intentos_fallidos=0',
                   'filtros_texto': 'id=?'},
 'INTERFAZ_0150': {'accion': 'eliminar', 'tabla': 'usuarios', 'filtros_texto': 'id=?'},
 'INTERFAZ_0151': {'accion': 'consultar',
                   'tabla': 'auditoria',
                   'columnas': '*',
                   'filtros_texto': '',
                   'orden_texto': 'id DESC',
                   'limite': 1000}}
