begin;
create extension if not exists pgcrypto;

create table if not exists usuarios (id bigint generated by default as identity primary key, usuario text unique not null, nombre text, password_hash text, rol text not null check (rol in ('usuario','desarrollador')), activo integer default 1, intentos_fallidos integer default 0, requiere_cambio_pass integer default 0, creado_en timestamptz);
create table if not exists app_config (clave text primary key, valor text, actualizado_en timestamptz);
create table if not exists catalogos (id bigint generated by default as identity primary key, categoria text not null, valor text not null, activo integer default 1, unique(categoria,valor));
create table if not exists productos (id bigint generated by default as identity primary key, item text unique not null, descripcion text, cliente text, familia text, activo integer default 1);
create table if not exists defectos (id bigint generated by default as identity primary key, codigo text unique not null, defecto text, tipo_defecto text, clasificacion text, activo integer default 1);
create table if not exists catalogo_naves_lineas (id bigint generated by default as identity primary key, nave text, linea text, sector text, linea_norm text, sector_norm text, orden integer default 0, activo integer default 1, unique(nave,linea,sector));
create table if not exists catalogo_formatos_entrega (id bigint generated by default as identity primary key, formato_nave text not null, tipo text not null, linea text not null, sector text not null, tipo_analisis text default '', orden_linea integer default 0, orden_sector integer default 0, activo integer default 1, unique(formato_nave,tipo,linea,sector,tipo_analisis));
create table if not exists catalogo_seguimientos_entrega (id bigint generated by default as identity primary key, nombre text unique not null, orden integer default 0, activo integer default 1);
create table if not exists catalogo_seguimientos_campos (id bigint generated by default as identity primary key, seguimiento_id bigint not null references catalogo_seguimientos_entrega(id), nombre text not null, tipo_campo text not null default 'Texto', opciones text default '', obligatorio integer default 0, orden integer default 0, activo integer default 1, unique(seguimiento_id,nombre));

create table if not exists pnc_registros (id bigint generated by default as identity primary key, folio text unique, fecha_apertura date, linea_sector text, nave text, item text, descripcion_producto text, cliente text, familia text, lote text, etapa text, codigo_defecto text, defecto text, tipo_defecto text, clasificacion text, turno text, supervisor text, analista text, responsable_detecta text, descripcion_defecto text, acciones_inmediatas text, disposicion text, cantidad_observada numeric default 0, cantidad_reproceso numeric default 0, cantidad_decomiso numeric default 0, cantidad_aprobado_segunda numeric default 0, cantidad_total_pnc numeric default 0, status text default 'ABIERTO', fecha_final_tratamiento date, observaciones text, material_hallado text, creado_por text, creado_en timestamptz, actualizado_por text, actualizado_en timestamptz, semana integer, categoria_inicial_pnc text, categoria_final_pnc text);
create table if not exists me_registros (id bigint generated by default as identity primary key, dia integer, mes integer, anio integer, nave text, linea_sector text, familia text, equipo_hallazgo text, item text, producto text, lote text, descripcion_hallazgo text, tipo text, particulas_halladas integer default 0, accion_contingente text, investigacion_origen text, analista_detecta text, supervisor_responsable text, acciones_evitar_incidencia text, creado_por text, creado_en timestamptz, etapa text, codigo_defecto text, semana integer, turno text, responsable_detecta text, acciones_inmediatas text, disposicion text, cantidad_observada numeric default 0, status text, categoria_inicial text, sector_hallazgo text, ubicacion_material text, actualizado_por text, actualizado_en timestamptz);
create table if not exists ddm_rx_registros (like me_registros including all);
alter table ddm_rx_registros add column if not exists id bigint generated by default as identity;

create table if not exists reclamos_registros (id bigint generated by default as identity primary key, fecha date, codigo_defecto text, descripcion_defecto text, fuente text, mercado text, pais_estado text, numero_caso text, item text, producto text, cliente text, familia text, descripcion_reclamo text, causa_raiz text, acciones_correctivas_contingentes text, comprobado text, cantidad_afectada numeric default 0, unidad text, sector text, estado_reclamo text, fecha_cierre date, tsp_numero text, caducidad text, lote text, nave text, pmd text, tipo_defecto text, clasificacion_defecto text, red_social text, creado_por text, creado_en timestamptz, actualizado_por text, actualizado_en timestamptz);
create index if not exists ix_reclamos_numero_caso on reclamos_registros ((upper(trim(numero_caso))));
create table if not exists devoluciones_registros (id bigint generated by default as identity primary key, fecha date, codigo_defecto text, defecto text, cedis text, pais_estado text, item text, producto text, cliente text, linea text, familia text, lote text, caducidad text, descripcion_defecto text, comprobado text, cantidad_afectada numeric default 0, unidad text, sector text, disposicion text, tsp_numero text, status text, nave text, creado_por text, creado_en timestamptz, actualizado_por text, actualizado_en timestamptz);

create table if not exists entregas_turno (id bigint generated by default as identity primary key, nave text, fecha date, analista text, turno text, referencia text, total_carga_datos numeric default 0, total_horas_trabajadas numeric default 0, creado_por text, creado_en timestamptz);
create table if not exists entregas_turno_lineas (id bigint generated by default as identity primary key, entrega_id bigint references entregas_turno(id) on delete cascade, grupo text, linea text, producto_descripcion text, horas_trabajadas numeric default 0, carga_spac numeric default 0, observaciones text, orden_fila integer default 0, nave_catalogo text);
create table if not exists entregas_turno_seguimientos (id bigint generated by default as identity primary key, entrega_id bigint references entregas_turno(id) on delete cascade, bloque text, registro_numero text, hoja_fisica text, carga_electronica text, correo text, descripcion_seguimiento text, datos_json jsonb default '{}'::jsonb, orden_fila integer default 0);
create table if not exists matriz_entrega (id bigint generated by default as identity primary key, fecha date not null, analista text not null, entrega_id bigint references entregas_turno(id) on delete set null, total_carga_datos numeric default 0, horas_nave1 numeric default 0, horas_nave2 numeric default 0, horas_nave3 numeric default 0, actualizado_en timestamptz, unique(fecha,analista));
create table if not exists metas_carga_spac (id bigint generated by default as identity primary key, tipo_entidad text not null, entidad text not null, periodo_tipo text not null, periodo_clave text not null, meta numeric default 0, actualizado_por text, actualizado_en timestamptz, unique(tipo_entidad,entidad,periodo_tipo,periodo_clave));
create table if not exists ajustes_diarios_spac (id bigint generated by default as identity primary key, tipo_entidad text not null, entidad text not null, fecha date not null, valor numeric, justificacion text, actualizado_por text, actualizado_en timestamptz, unique(tipo_entidad,entidad,fecha));

create table if not exists adjuntos (id bigint generated by default as identity primary key, registro_id bigint, folio text, nombre_original text, ruta_archivo text, tipo_archivo text, subido_por text, subido_en timestamptz);
create table if not exists auditoria (id bigint generated by default as identity primary key, usuario text, accion text, detalle text, fecha_hora timestamptz);

create table if not exists muestras_10_meses (id bigint generated by default as identity primary key, item text not null, descripcion text not null, lote text not null, destino text not null, numero_muestras numeric default 0, numero_corrugado numeric default 0, responsable text not null, observaciones text, creado_por text, creado_en timestamptz, actualizado_por text, actualizado_en timestamptz);
create table if not exists muestras_12_meses_alergeno (like muestras_10_meses including all);
create table if not exists muestras_12_meses_duvalin (like muestras_10_meses including all);
create table if not exists muestras_12_meses_nave2 (like muestras_10_meses including all);
create table if not exists muestras_15_meses (like muestras_10_meses including all);
create table if not exists muestras_18_meses (like muestras_10_meses including all);
create table if not exists muestras_24_meses (like muestras_10_meses including all);

insert into catalogo_seguimientos_entrega(nombre,orden) values
('Seguimiento a Contaminaciones',0),('Seguimiento a PNC´S',1),('Limpiezas',2),('Seguimiento a ORDENES DE FALLO',3),('GIRO / JUNTA DE EQUIPO',4)
on conflict(nombre) do nothing;

-- La app es Streamlit server-side. Se bloquea acceso directo anónimo a tablas.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
commit;
